// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:9b2de2d8-889f-48ad-a1e4-e916aaa15d9f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_VlJy6ejXE",
    "aws_user_pools_web_client_id": "6r94aa56kt79j2g8dkbm58i7ro",
    "oauth": {},
    "aws_bots": "enable",
    "aws_bots_config": [
        {
            "name": "ggg_openv",
            "alias": "$LATEST",
            "region": "us-east-1"
        }
    ]
};


export default awsmobile;
